spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: product
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
# Redis
  redis:
    database: 1
    timeout: 5000
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
  mvc:
    view:
      prefix:
      suffix: .ftl
  freemarker:
    charset: utf-8
    suffix: .ftl
    enabled: true
    prefix:
  http:
    multipart:
      enabled: true

