spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: product
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
# Redis数据库索引（默认为0）
  redis:
    database: 0
    timeout: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    cluster:
      max-redirects: 10
      nodes: 127.0.0.1:6080